[project]
name = 'clarity-nft'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.my-nft]
path = 'contracts/my-nft.clar'
clarity_version = 1

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
